/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/_portal'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin.admin'
import { Route as AuthenticatedPortalAgreementRouteImport } from './routes/_authenticated/_portal.agreement'
import { Route as AuthenticatedPortalBillingRouteImport } from './routes/_authenticated/_portal.billing'
import { Route as AuthenticatedPortalBriefRouteImport } from './routes/_authenticated/_portal.brief'
import { Route as AuthenticatedPortalDashboardRouteImport } from './routes/_authenticated/_portal.dashboard'
import { Route as AuthenticatedPortalDeliveryRouteImport } from './routes/_authenticated/_portal.delivery'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/_portal.documents'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/_portal.profile'
import { Route as AuthenticatedPortalProjectRouteImport } from './routes/_authenticated/_portal.project'
import { Route as AuthenticatedPortalServicesRouteImport } from './routes/_authenticated/_portal.services'
import { Route as AuthenticatedPortalSupportRouteImport } from './routes/_authenticated/_portal.support'
import { Route as AuthenticatedPortalWelcomeRouteImport } from './routes/_authenticated/_portal.welcome'
import { Route as AuthenticatedAdminAdminProjectIdRouteImport } from './routes/_authenticated/_admin.admin_.$projectId'
import { Route as AuthenticatedAdminAdminRibsRouteImport } from './routes/_authenticated/_admin.admin_.ribs'
import { Route as AuthenticatedPortalInvoiceInvoiceIdRouteImport } from './routes/_authenticated/_portal.invoice.$invoiceId'
import { Route as AuthenticatedPortalPayPaymentRequestIdRouteImport } from './routes/_authenticated/_portal.pay.$paymentRequestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPortalAgreementRoute =
  AuthenticatedPortalAgreementRouteImport.update({
    id: '/agreement',
    path: '/agreement',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalBillingRoute =
  AuthenticatedPortalBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalBriefRoute =
  AuthenticatedPortalBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDashboardRoute =
  AuthenticatedPortalDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDeliveryRoute =
  AuthenticatedPortalDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProjectRoute =
  AuthenticatedPortalProjectRouteImport.update({
    id: '/project',
    path: '/project',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalServicesRoute =
  AuthenticatedPortalServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSupportRoute =
  AuthenticatedPortalSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalWelcomeRoute =
  AuthenticatedPortalWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminAdminProjectIdRoute =
  AuthenticatedAdminAdminProjectIdRouteImport.update({
    id: '/admin_/$projectId',
    path: '/admin/$projectId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminRibsRoute =
  AuthenticatedAdminAdminRibsRouteImport.update({
    id: '/admin_/ribs',
    path: '/admin/ribs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPortalInvoiceInvoiceIdRoute =
  AuthenticatedPortalInvoiceInvoiceIdRouteImport.update({
    id: '/invoice/$invoiceId',
    path: '/invoice/$invoiceId',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPayPaymentRequestIdRoute =
  AuthenticatedPortalPayPaymentRequestIdRouteImport.update({
    id: '/pay/$paymentRequestId',
    path: '/pay/$paymentRequestId',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/agreement': typeof AuthenticatedPortalAgreementRoute
  '/billing': typeof AuthenticatedPortalBillingRoute
  '/brief': typeof AuthenticatedPortalBriefRoute
  '/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/delivery': typeof AuthenticatedPortalDeliveryRoute
  '/documents': typeof AuthenticatedPortalDocumentsRoute
  '/profile': typeof AuthenticatedPortalProfileRoute
  '/project': typeof AuthenticatedPortalProjectRoute
  '/services': typeof AuthenticatedPortalServicesRoute
  '/support': typeof AuthenticatedPortalSupportRoute
  '/welcome': typeof AuthenticatedPortalWelcomeRoute
  '/admin/$projectId': typeof AuthenticatedAdminAdminProjectIdRoute
  '/admin/ribs': typeof AuthenticatedAdminAdminRibsRoute
  '/invoice/$invoiceId': typeof AuthenticatedPortalInvoiceInvoiceIdRoute
  '/pay/$paymentRequestId': typeof AuthenticatedPortalPayPaymentRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/agreement': typeof AuthenticatedPortalAgreementRoute
  '/billing': typeof AuthenticatedPortalBillingRoute
  '/brief': typeof AuthenticatedPortalBriefRoute
  '/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/delivery': typeof AuthenticatedPortalDeliveryRoute
  '/documents': typeof AuthenticatedPortalDocumentsRoute
  '/profile': typeof AuthenticatedPortalProfileRoute
  '/project': typeof AuthenticatedPortalProjectRoute
  '/services': typeof AuthenticatedPortalServicesRoute
  '/support': typeof AuthenticatedPortalSupportRoute
  '/welcome': typeof AuthenticatedPortalWelcomeRoute
  '/admin/$projectId': typeof AuthenticatedAdminAdminProjectIdRoute
  '/admin/ribs': typeof AuthenticatedAdminAdminRibsRoute
  '/invoice/$invoiceId': typeof AuthenticatedPortalInvoiceInvoiceIdRoute
  '/pay/$paymentRequestId': typeof AuthenticatedPortalPayPaymentRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_portal/agreement': typeof AuthenticatedPortalAgreementRoute
  '/_authenticated/_portal/billing': typeof AuthenticatedPortalBillingRoute
  '/_authenticated/_portal/brief': typeof AuthenticatedPortalBriefRoute
  '/_authenticated/_portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/_authenticated/_portal/delivery': typeof AuthenticatedPortalDeliveryRoute
  '/_authenticated/_portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/_portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/_portal/project': typeof AuthenticatedPortalProjectRoute
  '/_authenticated/_portal/services': typeof AuthenticatedPortalServicesRoute
  '/_authenticated/_portal/support': typeof AuthenticatedPortalSupportRoute
  '/_authenticated/_portal/welcome': typeof AuthenticatedPortalWelcomeRoute
  '/_authenticated/_admin/admin_/$projectId': typeof AuthenticatedAdminAdminProjectIdRoute
  '/_authenticated/_admin/admin_/ribs': typeof AuthenticatedAdminAdminRibsRoute
  '/_authenticated/_portal/invoice/$invoiceId': typeof AuthenticatedPortalInvoiceInvoiceIdRoute
  '/_authenticated/_portal/pay/$paymentRequestId': typeof AuthenticatedPortalPayPaymentRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/onboarding'
    | '/admin'
    | '/agreement'
    | '/billing'
    | '/brief'
    | '/dashboard'
    | '/delivery'
    | '/documents'
    | '/profile'
    | '/project'
    | '/services'
    | '/support'
    | '/welcome'
    | '/admin/$projectId'
    | '/admin/ribs'
    | '/invoice/$invoiceId'
    | '/pay/$paymentRequestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/onboarding'
    | '/admin'
    | '/agreement'
    | '/billing'
    | '/brief'
    | '/dashboard'
    | '/delivery'
    | '/documents'
    | '/profile'
    | '/project'
    | '/services'
    | '/support'
    | '/welcome'
    | '/admin/$projectId'
    | '/admin/ribs'
    | '/invoice/$invoiceId'
    | '/pay/$paymentRequestId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/_authenticated/_admin'
    | '/_authenticated/_portal'
    | '/_authenticated/onboarding'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_portal/agreement'
    | '/_authenticated/_portal/billing'
    | '/_authenticated/_portal/brief'
    | '/_authenticated/_portal/dashboard'
    | '/_authenticated/_portal/delivery'
    | '/_authenticated/_portal/documents'
    | '/_authenticated/_portal/profile'
    | '/_authenticated/_portal/project'
    | '/_authenticated/_portal/services'
    | '/_authenticated/_portal/support'
    | '/_authenticated/_portal/welcome'
    | '/_authenticated/_admin/admin_/$projectId'
    | '/_authenticated/_admin/admin_/ribs'
    | '/_authenticated/_portal/invoice/$invoiceId'
    | '/_authenticated/_portal/pay/$paymentRequestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_portal': {
      id: '/_authenticated/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_portal/agreement': {
      id: '/_authenticated/_portal/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AuthenticatedPortalAgreementRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/billing': {
      id: '/_authenticated/_portal/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedPortalBillingRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/brief': {
      id: '/_authenticated/_portal/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof AuthenticatedPortalBriefRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/dashboard': {
      id: '/_authenticated/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedPortalDashboardRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/delivery': {
      id: '/_authenticated/_portal/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedPortalDeliveryRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/documents': {
      id: '/_authenticated/_portal/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/profile': {
      id: '/_authenticated/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/project': {
      id: '/_authenticated/_portal/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthenticatedPortalProjectRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/services': {
      id: '/_authenticated/_portal/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedPortalServicesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/support': {
      id: '/_authenticated/_portal/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedPortalSupportRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/welcome': {
      id: '/_authenticated/_portal/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedPortalWelcomeRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_admin/admin_/$projectId': {
      id: '/_authenticated/_admin/admin_/$projectId'
      path: '/admin/$projectId'
      fullPath: '/admin/$projectId'
      preLoaderRoute: typeof AuthenticatedAdminAdminProjectIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin_/ribs': {
      id: '/_authenticated/_admin/admin_/ribs'
      path: '/admin/ribs'
      fullPath: '/admin/ribs'
      preLoaderRoute: typeof AuthenticatedAdminAdminRibsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_portal/invoice/$invoiceId': {
      id: '/_authenticated/_portal/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/invoice/$invoiceId'
      preLoaderRoute: typeof AuthenticatedPortalInvoiceInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_portal/pay/$paymentRequestId': {
      id: '/_authenticated/_portal/pay/$paymentRequestId'
      path: '/pay/$paymentRequestId'
      fullPath: '/pay/$paymentRequestId'
      preLoaderRoute: typeof AuthenticatedPortalPayPaymentRequestIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminAdminProjectIdRoute: typeof AuthenticatedAdminAdminProjectIdRoute
  AuthenticatedAdminAdminRibsRoute: typeof AuthenticatedAdminAdminRibsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  AuthenticatedAdminAdminProjectIdRoute: AuthenticatedAdminAdminProjectIdRoute,
  AuthenticatedAdminAdminRibsRoute: AuthenticatedAdminAdminRibsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAgreementRoute: typeof AuthenticatedPortalAgreementRoute
  AuthenticatedPortalBillingRoute: typeof AuthenticatedPortalBillingRoute
  AuthenticatedPortalBriefRoute: typeof AuthenticatedPortalBriefRoute
  AuthenticatedPortalDashboardRoute: typeof AuthenticatedPortalDashboardRoute
  AuthenticatedPortalDeliveryRoute: typeof AuthenticatedPortalDeliveryRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalProjectRoute: typeof AuthenticatedPortalProjectRoute
  AuthenticatedPortalServicesRoute: typeof AuthenticatedPortalServicesRoute
  AuthenticatedPortalSupportRoute: typeof AuthenticatedPortalSupportRoute
  AuthenticatedPortalWelcomeRoute: typeof AuthenticatedPortalWelcomeRoute
  AuthenticatedPortalInvoiceInvoiceIdRoute: typeof AuthenticatedPortalInvoiceInvoiceIdRoute
  AuthenticatedPortalPayPaymentRequestIdRoute: typeof AuthenticatedPortalPayPaymentRequestIdRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAgreementRoute: AuthenticatedPortalAgreementRoute,
  AuthenticatedPortalBillingRoute: AuthenticatedPortalBillingRoute,
  AuthenticatedPortalBriefRoute: AuthenticatedPortalBriefRoute,
  AuthenticatedPortalDashboardRoute: AuthenticatedPortalDashboardRoute,
  AuthenticatedPortalDeliveryRoute: AuthenticatedPortalDeliveryRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalProjectRoute: AuthenticatedPortalProjectRoute,
  AuthenticatedPortalServicesRoute: AuthenticatedPortalServicesRoute,
  AuthenticatedPortalSupportRoute: AuthenticatedPortalSupportRoute,
  AuthenticatedPortalWelcomeRoute: AuthenticatedPortalWelcomeRoute,
  AuthenticatedPortalInvoiceInvoiceIdRoute:
    AuthenticatedPortalInvoiceInvoiceIdRoute,
  AuthenticatedPortalPayPaymentRequestIdRoute:
    AuthenticatedPortalPayPaymentRequestIdRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
